### PR TITLE
Always configure framework provider in `Configure` function

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

This fixes an issue that provider config in tf files can't go though and reach resource code during testing.

## ✔️ How to Test
You can verify this fixes the issue in #1678

After applying this change, [the obj test run](https://github.com/linode/terraform-provider-linode/actions/runs/12063045505/job/33637639685) was successful

Otherwise it would [fail](https://github.com/linode/terraform-provider-linode/actions/runs/12063048722/job/33637757741) or [need multiple attempts to be successful](https://github.com/linode/terraform-provider-linode/actions/runs/12063048722/job/33637645987)

### CODE REVIEW

**Comment by zliang-akamai** [comment]
CC: @tchinmai7

**Review by lgarber-akamai — APPROVED** [review]
All relevant tests are passing, great work!

**Review by tchinmai7 — APPROVED** [review]
Changes look like they don't affect crossplane

**Review by yec-akamai — APPROVED** [review]
LGTM

**Pull request merged**
