### PR TITLE
Update existing resources to support VPC related linodego changes

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description
This is to align with the breaking code changes happened in linodego for the VPC project.

## Test

`make testacc PKG_NAME=linode/instanceconfig`

`make testacc PKG_NAME=linode/instance`

### CODE REVIEW

**Review by lgarber-akamai — APPROVED** [review]
Looks good to me! Maybe this should point to a VPC project branch since this breaking change will correspond to VPC support being released.

**Review by jriddle-linode — APPROVED** [review]
Agree with Lena need to change base.

**Comment by zliang-akamai** [comment]
Thanks for changing the base branch! I forgot to do so, lol.

**Comment by zliang-akamai** [comment]
Also, we might want to switch the linodego dependency to be the vpc feature branch.

**Comment by yec-akamai** [comment]
> ~Also, we might want to switch the linodego dependency to be the vpc feature branch.~
> 
> But we can't do that because our branch name contains `/`, lol https://www.reddit.com/r/golang/comments/ikl3d2/gomod_replace_with_specific_branch_rather_than/jdx60q5/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Can we just change the name of the vpc branch to overcome this issue?

**Comment by lgarber-akamai** [comment]
@zliang-akamai For the time being maybe we could pin to the latest commit on the linodego VPC feature branch?

**Comment by zliang-akamai** [comment]
@lgarber-akamai Yes, I think that would be a good idea. But if we can follow @yec-akamai's suggestion to change the branch name to be something like `project-vpc`, we can let go to do it automatically by `go get github.com/linode/linodego@project-vpc`. What do you think?

**Pull request merged**
