### PR TITLE
fix: Fix LDE-related test failures

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This pull request resolves the following test errors that were occurring after the LDE project branch was merged to dev:

* Capability string enums became out of date due to a breaking change that wasn't accounted for in the LDE branch
* `pool.0.disk_encryption` -> `pools.0.disk_encryption`

## ✔️ How to Test

The following test steps assume you have pulled down this PR locally.

### Integration Tests

```
make PKG_NAME=linode/instance int-test
make PKG_NAME=linode/lke int-test
```

### CODE REVIEW

**Review by ezilber-akamai — COMMENTED** [review]
I got a failure when running the instance integration tests:
```
=== NAME  TestAccResourceInstance_diskEncryption
    resource_test.go:2535: Step 1/4 error: Check failed: Check 6/6 error: linode_instance.foobar: Attribute 'disk_encryption' expected "enabled", got "disabled"
```

**Comment by yec-akamai** [comment]
I also get the above error, and another one:
```
 [400] Additional IPv4 addresses require technical justification.  Please
        contact support describing your requirement
--- FAIL: TestAccResourceInstance_ipv4Sharing (122.27s)
```

**Comment by ezilber-akamai** [comment]
> I also get the above error, and another one:
> 
> ```
>  [400] Additional IPv4 addresses require technical justification.  Please
>         contact support describing your requirement
> --- FAIL: TestAccResourceInstance_ipv4Sharing (122.27s)
> ```

Interesting, I didn't get this one. Maybe its intermittent?

**Review by zliang-akamai — APPROVED** [review]
Tested and both passed. Nice work!

**Review by yec-akamai — APPROVED** [review]
Tests passed locally, nice fix!

**Review by ezilber-akamai — APPROVED** [review]
Passing locally for me as well!

**Pull request merged**
