### PR TITLE
Add timeout block support to BaseResourceConfig and `linode_rdns` resource

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

This PR separates timeout logic from [the volume migration PR](https://github.com/linode/terraform-provider-linode/pull/1240) as the breaking change might delay the volume migration work.

This PR also implements multiple helper functions for handling pointer values.

## ✔️ How to Test

~~We currently don't have any resource which has time consuming operations, so we probably can't test it in this PR.~~

~~However, in [the volume migration PR](https://github.com/linode/terraform-provider-linode/pull/1240), many operations are time consuming like resizing or creation. And that PR contains basically same code for handling timeout, so you can pull it and test it there.~~

Thanks @lgarber-akamai's idea! I added timeout support to `linode_rdns` resource. So now it can be tested with `linode_rdns` resource.

## Automated Testing

`make int-test PKG_NAME="linode/rdns"` 

## Manual Testing

```terraform
resource "linode_instance" "foobar" {
    label = "mylinode"
    image = "linode/debian12"
    type = "g6-nanode-1"
    region = "us-mia"
}

resource "linode_rdns" "foobar" {
    address = "${linode_instance.foobar.ip_address}"
    rdns    = "${linode_instance.foobar.ip_address}.nip.io"
    wait_for_available = true

    timeouts {
        create = "15m"
        update = "15m"
    }
}
```

You can verify if this config is applied successfully with Terraform, and then you can change the timeout to be a very small value, such as `1ms`, to verify it can fail in the case of timeout.

### CODE REVIEW

**Review by lgarber-akamai — COMMENTED** [review]
@zliang-akamai This looks great so far, thanks for breaking it out into a separate PR!

For testing purposes, could you also implement the configurable timeouts in a resource (e.g. `linode_rdns`) as a part of this PR?

**Comment by zliang-akamai** [comment]
Hey @lgarber-akamai, I just added the timeout and related tests to `linode_rdns` resource. Thank you for the feedback!

**Review by lgarber-akamai — APPROVED** [review]
LGTM, nice work!

**Review by jriddle-linode — APPROVED** [review]
Everything passes locally!

**Pull request merged**
