### PR TITLE
fix: Increase complexity for root passwords used in tests (again)

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change alters some acctest suite passwords to be compliant with the raised root password requirements enforced by the API.

## ✔️ How to Test

```
make testacc
```

### CODE REVIEW

**Comment by lgarber-akamai** [comment]
/acctest sha=ca6c4f97390007e3b8084294b5f35f395b534a03 pkg=linode/...

**Comment by lgarber-akamai** [comment]
/acctest sha=439f067fd3899758e0d9f86f79b82e9d5a492d89 pkg=linode/...

**Review by yec-akamai — APPROVED** [review]
LGTM! Just curious, how do we know that the complexity for the root passwords need to be increased? Should we keep us updated with any docs/announcement, or did we start to see the api calls failed?

**Review by zliang-akamai — APPROVED** [review]

**Comment by lgarber-akamai** [comment]
> LGTM! Just curious, how do we know that the complexity for the root passwords need to be increased? Should we keep us updated with any docs/announcement, or did we start to see the api calls failed?

Great question! The raised password requirements by the API were planned, but in this case I just noticed some related failures in our integration test suite

**Pull request merged**
