### PR TITLE
Apply `FrameworkSafeInt64ToInt`

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

Making int64 to int conversion safer.

## ✔️ How to Test

```
make unittest
make PKG_NAME=linode/databasemysql testacc
make PKG_NAME=linode/databasepostgresql testacc
make PKG_NAME=linode/domain testacc
make PKG_NAME=linode/domainrecord testacc
make PKG_NAME=linode/domainzonefile testacc
make PKG_NAME=linode/firewall testacc
make PKG_NAME=linode/instancenetworking testacc
make PKG_NAME=linode/ipv6range testacc
make PKG_NAME=linode/nbconfig testacc
make PKG_NAME=linode/nbnode testacc
make PKG_NAME=linode/objkey testacc
make PKG_NAME=linode/sshkey testacc
make PKG_NAME=linode/volume testacc
```

### CODE REVIEW

**Comment by lgarber-akamai** [comment]
E2E test run: https://github.com/linode/terraform-provider-linode/actions/runs/6535933399

**Review by jriddle-linode — APPROVED** [review]

**Comment by amisiorek-akamai** [comment]
Is the E2E failing expected?

**Comment by zliang-akamai** [comment]
@amisiorek-akamai Thanks for bringing it up! It isn't expected to fail, but that's was another issue and unrelated to the change in this PR.

@lgarber-akamai I will do a rebase today. Thanks for the reminder!

**Comment by zliang-akamai** [comment]
Hi @lgarber-akamai, I think this PR is now ready to be reviewed.

**Review by lgarber-akamai — APPROVED** [review]
All relevant tests are passing, nice work!

**Pull request merged**
