### PR TITLE
ref: change makefile to meet dx standards

### PR DESCRIPTION
**Pull request by jriddle-linode**
## 📝 Description

**What does this PR do and why is this change necessary?**

Update makefile and workflows to match new DX standard document.

### CODE REVIEW

**Review by lgarber-akamai — COMMENTED** [review]
Looks great! Could you also update the references to the new targets in the README?

**Comment by jriddle-linode** [comment]
> Looks great! Could you also update the references to the new targets in the README?

I knew i was forgetting something..

**Review by lgarber-akamai — APPROVED** [review]
Looks good!

**Review by zliang-akamai — APPROVED** [review]
LGTM!

**Pull request merged**
