### PR TITLE
fix: Retry on database wait operation requests

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change alters the status polling logic in database-related resources to retry on `502` responses from the API within a certain tolerance. For the databases service, these errors do not necessarily reflect an internal error and instead may be the result of a transient error. This should significantly improve E2E test reliability.

Blocked by https://github.com/linode/linodego/pull/319

## ✔️ How to Test

```
make PKG_NAME=linode/databasemysql testacc
```

### CODE REVIEW

**Comment by lgarber-akamai** [comment]
/acctest sha=c99eb360cb287341a33dc06f890c2dad371b29b0 pkg=linode/databasemysql

**Comment by lgarber-akamai** [comment]
/acctest sha=c99eb360cb287341a33dc06f890c2dad371b29b0 pkg=linode/databaseaccesscontrols

**Comment by lgarber-akamai** [comment]
/acctest sha=cc0f58708740afaef8cfc9a8727511604f8a8b97 pkg=linode/databasemysql

**Comment by lgarber-akamai** [comment]
/acctest sha=cc0f58708740afaef8cfc9a8727511604f8a8b97 pkg=linode/databaseaccesscontrols

**Comment by lgarber-akamai** [comment]
/acctest sha=cc0f58708740afaef8cfc9a8727511604f8a8b97 pkg=linode/...

**Review by zliang-akamai — APPROVED** [review]
Nice work!

**Comment by zliang-akamai** [comment]
/acctest sha=cc0f58708740afaef8cfc9a8727511604f8a8b97 pkg=linode/...

**Comment by zliang-akamai** [comment]
/acctest sha=0202d41a6742d78f56845b1f04f73916221bf6f8 pkg=linode/...

**Comment by zliang-akamai** [comment]
Wondering if we should use `MinRetryDelayMilliseconds` and `MaxRetryDelayMilliseconds` from the config.

https://github.com/linode/terraform-provider-linode/blob/c8592580a3f9cd115075bbd9ecd4fc13ca18a676/linode/provider.go#L271

But since I can't find these config values were used anywhere else, maybe we can remove these config values from config schema instead? Was there any historic context info regarding these config?

**Comment by lgarber-akamai** [comment]
@zliang-akamai 

> Wondering if we should use MinRetryDelayMilliseconds and MaxRetryDelayMilliseconds from the config.

That's a good point! It'd probably be a good idea to keep retry timings configurable.

> But since I can't find where these config values were used anywhere else, maybe we can just remove these config values from config schema instead?

These configs are passed into the linodego client and are used for retrying on 408 responses:
- https://github.com/linode/terraform-provider-linode/blob/dev/linode/helper/config.go#L94
- https://github.com/linode/linodego/blob/main/client.go#L319-L329

Hope that clears things up!

**Comment by zliang-akamai** [comment]
@lgarber-akamai Thank you for the context info!

**Review by zliang-akamai — APPROVED** [review]

**Review by zliang-akamai — APPROVED** [review]

**Review by ezilber-akamai — APPROVED** [review]

**Pull request merged**
